In [ ]:
from PIL import Image
import numpy as np

In [ ]:
flower=Image.open("photo.jpg")

In [ ]:
flower

In [27]:
# image changes into numpy numbers 
arr=np.array(flower)
arr

array([[[ 34,  57,  39],
        [ 33,  56,  38],
        [ 33,  56,  38],
        ...,
        [215, 235, 236],
        [215, 235, 236],
        [215, 235, 236]],

       [[ 34,  57,  39],
        [ 33,  56,  38],
        [ 33,  56,  38],
        ...,
        [215, 235, 236],
        [215, 235, 236],
        [215, 235, 236]],

       [[ 34,  57,  39],
        [ 34,  57,  39],
        [ 33,  56,  38],
        ...,
        [215, 235, 236],
        [215, 235, 236],
        [215, 235, 236]],

       ...,

       [[ 56, 102,  40],
        [ 56, 102,  40],
        [ 56, 101,  42],
        ...,
        [218, 234, 234],
        [218, 234, 234],
        [218, 234, 234]],

       [[ 56, 102,  40],
        [ 56, 102,  40],
        [ 56, 101,  42],
        ...,
        [218, 234, 234],
        [218, 234, 234],
        [218, 234, 234]],

       [[ 56, 102,  40],
        [ 56, 102,  40],
        [ 56, 101,  42],
        ...,
        [219, 235, 235],
        [219, 235, 235],
        [219, 235, 235]]

In [ ]:
person=Image.open("photo1.jpg")

In [ ]:
person

In [25]:
arr2=np.array(person)
arr2

array([[[122, 179, 190],
        [122, 179, 190],
        [121, 178, 189],
        ...,
        [ 99, 166, 183],
        [ 94, 166, 181],
        [ 86, 162, 176]],

       [[119, 177, 188],
        [118, 176, 187],
        [118, 176, 187],
        ...,
        [ 99, 164, 182],
        [ 91, 163, 178],
        [ 84, 158, 171]],

       [[115, 175, 186],
        [115, 175, 186],
        [115, 175, 186],
        ...,
        [ 94, 160, 176],
        [ 87, 154, 170],
        [ 80, 148, 161]],

       ...,

       [[149, 167, 177],
        [147, 167, 176],
        [146, 166, 175],
        ...,
        [ 70,  38,  49],
        [ 67,  39,  51],
        [ 68,  42,  55]],

       [[150, 167, 175],
        [149, 168, 175],
        [148, 168, 175],
        ...,
        [ 75,  35,  44],
        [ 75,  39,  49],
        [ 72,  41,  49]],

       [[150, 167, 175],
        [149, 168, 175],
        [149, 168, 175],
        ...,
        [ 75,  32,  41],
        [ 74,  37,  45],
        [ 73,  38,  45]]

In [ ]:
cat=Image.open("cat.jpg")
cat

In [26]:
arr3=np.array(cat)
arr3

array([[[227, 232, 238],
        [228, 233, 239],
        [228, 233, 239],
        ...,
        [232, 239, 247],
        [232, 239, 247],
        [232, 239, 247]],

       [[228, 233, 239],
        [228, 233, 239],
        [228, 233, 239],
        ...,
        [232, 239, 247],
        [232, 239, 247],
        [232, 239, 247]],

       [[228, 233, 239],
        [228, 233, 239],
        [228, 233, 239],
        ...,
        [232, 239, 247],
        [232, 239, 247],
        [232, 239, 247]],

       ...,

       [[244, 248, 251],
        [244, 248, 251],
        [244, 248, 251],
        ...,
        [246, 250, 253],
        [246, 250, 253],
        [246, 250, 253]],

       [[244, 248, 251],
        [244, 248, 251],
        [244, 248, 251],
        ...,
        [245, 249, 252],
        [245, 249, 252],
        [245, 249, 252]],

       [[244, 248, 251],
        [244, 248, 251],
        [244, 248, 251],
        ...,
        [245, 249, 252],
        [245, 249, 252],
        [245, 249, 252]]

In [ ]:
yellow=Image.open("yellow.png")
yellow

In [28]:
arr4=np.array(yellow)
arr4

array([[[253, 255,   4],
        [253, 255,   4],
        [253, 255,   4],
        ...,
        [255, 254,   0],
        [255, 255,   0],
        [255, 255,   0]],

       [[253, 255,   4],
        [253, 255,   4],
        [253, 255,   4],
        ...,
        [255, 254,   0],
        [255, 255,   0],
        [255, 255,   0]],

       [[253, 255,   4],
        [253, 255,   4],
        [253, 255,   4],
        ...,
        [255, 254,   0],
        [255, 255,   0],
        [255, 255,   0]],

       ...,

       [[253, 255,   0],
        [253, 255,   0],
        [253, 255,   2],
        ...,
        [255, 254,   4],
        [255, 252,  14],
        [255, 251,  20]],

       [[253, 255,   0],
        [253, 255,   0],
        [253, 255,   2],
        ...,
        [255, 254,   6],
        [254, 254,  17],
        [254, 253,  23]],

       [[253, 255,   0],
        [253, 255,   2],
        [253, 255,   4],
        ...,
        [255, 254,   6],
        [254, 254,  19],
        [254, 252,  25]]

In [ ]:
#display 1 grid
import matplotlib.pyplot as  plt
plt.imshow([[arr[5,5]]])
plt.show()